=== tie0913/CWEB-180/src/LO9/XMLAndDTDPractice/Student.dtd
<!ELEMENT student (name, courses*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT courses (course+)>
<!ELEMENT course (code, name, registered?)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT registered EMPTY>

=== tie0913/CWEB-180/src/LO9/XMLAndDTDPractice/Student.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE student SYSTEM "Student.dtd">
<student>
    <name>Tie Wang</name>
    <courses>
        <course>
            <code>CWEB180</code>
            <name>Web Site Development</name>
            <registered/>
        </course>
        <course>
            <code>CWEB 190</code>
            <name>Internet Programming/Web Application</name>
        </course>
    </courses>
</student>
