=== tie0913/CWEB-180/src/LO9/Solution/student.dtd
<!ELEMENT student (name,course+)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT course (courseNumber,courseName,registered)>
        <!ELEMENT courseNumber (#PCDATA)>
        <!ELEMENT courseName (#PCDATA)>
        <!ELEMENT registered EMPTY>
        <!ATTLIST registered status CDATA #REQUIRED>

=== tie0913/CWEB-180/src/LO9/Solution/student.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE student SYSTEM "student.dtd">
<student>
    <name>your name</name>
    <course>
        <courseNumber>CWEB 180</courseNumber>
        <courseName>Web Site Development</courseName>
        <registered status="yes" />
    </course>
    <course>
        <courseNumber>CWEB 190</courseNumber>
        <courseName>Internet Programming/Web Applications 1</courseName>
        <registered status="no" />
    </course>
</student>
